# WARNING: Generated by the platform, do not modify

FROM ${coalesce(runtime_image, "mcr.microsoft.com/dotnet/aspnet:6.0")} AS base
WORKDIR /app
%{ for port in ports ~}
EXPOSE ${port}
%{ endfor ~}

FROM ${coalesce(build_image, "mcr.microsoft.com/dotnet/sdk:6.0")} AS build
WORKDIR /src
COPY ["${csproj_path}", "."]
RUN dotnet restore "./${csproj_name}"
COPY . .
WORKDIR "/src/."
RUN dotnet build "${csproj_name}" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "${csproj_name}" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "${trimsuffix(csproj_name, ".csproj")}.dll"]